import type { Metadata } from 'next';
import './globals.css';
import _TrpcProvider from '@/providers/query.provider';
import { Alexandria } from 'next/font/google';
import { Toaster } from '@invoice/ui/sonner';
import { ThemeProvider } from '@/providers/theme-provider';

const alexandria = Alexandria({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '600'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alexandria.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <_TrpcProvider>{children}</_TrpcProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
