import type { Metadata } from 'next';
import './globals.css';
import _TrpcProvider from '@/providers/query.provider';
import { Alexandria } from 'next/font/google';
import { Navbar } from '@/components/custom/navbar';
const alexandria = Alexandria({
  subsets: ['latin'],
  weight: ['400', '600'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${alexandria.variable} antialiased`}>
        <_TrpcProvider>
          <Navbar></Navbar>
          {children}</_TrpcProvider>
      </body>
    </html>
  );
}
